// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfiownsuwnzyyotbdbgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmaW93bnN1d256eXlvdGJkYmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTc1OTMsImV4cCI6MjA3MTY5MzU5M30.3gKTtyxv7Z-jdBy17Pp681a_oRsuh0yjo9DHs7SeByA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});